#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

startLoc=$HOME/.config/xinit.d	
if [ -d ~/.config/xinit.d/ ] ; then
	for f in ~/.config/xinit.d/?*.sh ; do
	  [ -x "$f" ] && . "$f"
	done
	unset f
fi

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export GLFW_IM_MODULE=ibus

# start the window manager which is i3 by default but can be changed by passing a different window manager as an argument like kde or gnome

# every window manager has a different syntax to start it decide this switch case checks which window manager to start
case $1 in
    kde)
        export DESKTOP_SESSION=plasma 
        exec startplasma-x11
        ;;
    gnome)
        exec gnome-session
        ;;
    *)
        exec i3
        ;;
esac
