#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus on
yabai -m config window_placement second_child
yabai -m config window_opacity on
yabai -m config window_shadow on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config window_animation_duration 0.0

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# space 1: terminals
yabai -m rule --add app="iTerm2" space=^1
yabai -m rule --add app="kitty" space=^1

source ~/.config/yabai/rules/default

# things which create floating children
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Stats" manage=off mouse_follows_focus=off
yabai -m rule --add app="iStat Menus" manage=off mouse_follows_focus=off
#yabai -m rule --add app="Things" grid=10:3:1:1:1:8 mouse_follows_focus=on sticky=on
yabai -m rule --add app="Chromium" manage=off mouse_follows_focus=off
yabai -m rule --add app="choose" manage=off mouse_follows_focus=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off
yabai -m rule --add app="Raycast" title="Settings" manage=off mouse_follows_focus=off
yabai -m rule --add app="Electron" manage=off mouse_follows_focus=off

# pygame popups
yabai -m rule --add app="Python" manage=off mouse_follows_focus=off
