#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    ls --color=auto &> /dev/null && alias ls='ls --color=auto' || alias ls='ls -G'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias bye='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias refresh='source ~/.bashrc'
alias e='exit'
alias update='bash $YOZORA_PATH/install.sh'
