#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    ls --color=auto &> /dev/null && alias ls='ls --color=auto' || alias ls='ls -G'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias bye='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias refresh='source ~/.bashrc'
alias e='exit'
alias c='clear'
alias h='history'
alias ll='ls -l'
alias home='~'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias n='nvim'
alias start='startx ~/.xinitrc $1'

dotnet_install() {
  version=${1:-"latest"}
  type=${2:-"channel"}

  if [[ $type == "channel" ]]; then
    type="channel LTS"
  fi 

  if [[ $type == "runtime" ]]; then
    type="runtime dotnet"
  fi

  sudo bash $YOZORA_PATH/tools/dotnet-install.sh --install-dir /usr/share/dotnet -$type -version $version
}
# Directory navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Example usage: `update` or `update <package_collection>`
alias update='bash $YOZORA_PATH/install.sh $1'
