#!/usr/bin/env bash


source ~/.config/yozora/git-prompt.sh

PS1=""
PS1+="╔═╦═══ [\[\e[32m\]\u\[\e[0m\]@\[\e[36m\]\h\[\e[0m\]] - (\[\e[39;1m\]\j\[\e[0m\]) - [\[\e[34m\]\w\e[1;33m\$(__git_ps1 \" (%s)\")\e[0m\[\e[0m\]]"
PS1+="\n"
PS1+="╚═╩═ *** \[\e[0m\]"

export PS1;
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
