#!/usr/bin/env bash

install_krew() {
  (
    set -x; cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew
  )
}

dotnet_install() {
  version=${1:-"latest"}
  type=${2:-"channel"}

  if [[ $type == "channel" ]]; then
    type="channel LTS"
  fi 

  if [[ $type == "runtime" ]]; then
    type="runtime dotnet"
  fi

  sudo bash $YOZORA_PATH/tools/dotnet-install.sh --install-dir /usr/share/dotnet -$type -version $version
}

# Download the bashrc components from the yozora repository
brc() {
  operation=${1:-"download"}
  bash $YOZORA_PATH/shell/bash/updater.sh --$operation
}

# Custom git clone function
# use with --user <user> --host <host> --is_ssh <is_ssh> --target_dir <target_dir>
gclone() {
  # Parse the arguments in switch case
  while [[ $# -gt 0 ]]; do
    case $1 in
      "--user"|"-u")
        user=${2:-"$(whoami)"}
        shift
        shift
        ;;
      "--host"|"-h")
        host=${2:-"github.com"}
        shift
        shift
        ;;
      "--is_ssh")
        is_ssh=${2:-"true"}
        shift
        shift
        ;;
      "--target_dir"|"-t")
        target_dir=${2:-""}
        shift
        shift
        ;;
      *)
        repo=$1
        shift
        ;;
    esac
  done

  if [[ -z $user ]]; then
    echo "No user or global user specified"
    echo "usage: gclone <repo> [user] [host] [is_ssh]"
    return 1
  fi

  if [[ -z $repo ]]; then
    echo "No repository specified"
    echo "usage: gclone <repo> [user] [host] [is_ssh]"
    return 1
  fi
  
  if [[ $is_ssh == "true" ]]; then
    git clone git@$host:$user/$repo.git $target_dir
  else
    git clone https://$host/$user/$repo.git $target_dir
  fi
}

