#!/usr/bin/env bash

# if [ "`whoami`" = "root" ]; then
#     lpath="/root/bin"
#     User=$'\[\e[31;40m\]\u\[\e[0m\]@\[\e[36m\]\h\[\e[0m\]'
# else
#     lpath="/home/`whoami`/bin"
#     User=$'\[\e[32m\]\u\[\e[0m\]@\[\e[36m\]\h\[\e[0m\]'
# fi

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
else
	color_prompt=
fi

# See: http://aperiodic.net/screen/title_examples#setting_the_title_to_the_name_of_the_running_program
case $TERM in screen*)
  PS1=${PS1}'\[\033k\033\\\]'
esac

PS1=""
PS1+="╔═╦═══ [\[\e[32m\]\u\[\e[0m\]@\[\e[36m\]\h\[\e[0m\]] - (\[\e[39;1m\]\j\[\e[0m\]) - [\[\e[34m\]\w\e[1;33m\$(__git_ps1 \" (%s)\")\e[0m\[\e[0m\]]"
PS1+="\n"
PS1+="╚═╩═ *** \[\e[0m\]"

export PS1;
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
