#!/usr/bin/env bash

install_krew() {
  (
    set -x; cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew
  )
}

dotnet_install() {
  version=${1:-"latest"}
  type=${2:-"channel"}

  if [[ $type == "channel" ]]; then
    type="channel LTS"
  fi 

  if [[ $type == "runtime" ]]; then
    type="runtime dotnet"
  fi

  sudo bash $YOZORA_PATH/tools/dotnet-install.sh --install-dir /usr/share/dotnet -$type -version $version
}

# Download the bashrc components from the yozora repository
brc() {
  operation=${1:-"download"}
  bash $YOZORA_PATH/shell/bash/updater.sh --$operation
}

# Custom git clone function
gclone() {
  repo=$1
  user=${2:-"joshika39"}
  host=${3:-"github.com"}
  is_ssh=${4:-"true"}

  if [[ -z $repo ]]; then
    echo "No repository specified"
    echo "usage: gclone <repo> [user] [host] [is_ssh]"
    return 1
  fi
  
  if [[ $is_ssh == "true" ]]; then
    git clone git@$host:$user/$repo.git
  else
    git clone https://$host/$user/$repo.git
  fi
}

