#!/opt/homebrew/bin/fish

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Prepare for work
# @raycast.mode silent

# Documentation:
# @raycast.author joshika39
# @raycast.authorURL https://raycast.com/joshika39

bash $HOME/scripts/create-spaces.sh

echo "Killing unnecessary apps..."

pkill -x Safari
pkill -x "Keychain Access"
pkill -x Things3
pkill -x Obsidian

sh ~/.config/yabai/rules/work
sh ~/.config/yabai/rules/work apply
