#!/usr/bin/env sh

COMMAND=${1:-add}
FOLLOW=$(if [ "${COMMAND}" = "add" ]; then echo "^"; else echo ""; fi)

[ -z "${FOLLOW}" ] && exit 0

# space 3: web
yabai -m rule --${COMMAND} app="Safari" title="personal*" space=${FOLLOW}3

# space 6: todo and notes and brainstorming
yabai -m rule --${COMMAND} app="Things" space=${FOLLOW}6
yabai -m rule --${COMMAND} app="Notes" space=${FOLLOW}6
yabai -m rule --${COMMAND} app="Freeform" space=${FOLLOW}6
yabai -m rule --${COMMAND} app="Obsidian" space=${FOLLOW}6
