#!/usr/bin/env python3

import argparse
from pathlib import Path
import os
import sys
from glob import glob

from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

def get_exif(path: str):
    with Image.open(path) as img:
        raw = img._getexif() or {}

    exif = {TAGS.get(k, k): v for k, v in raw.items()}

    if "GPSInfo" in exif:
        gps = {}
        for k, v in exif["GPSInfo"].items():
            gps[GPSTAGS.get(k, k)] = v
        exif["GPSInfo"] = gps

    return exif

parser = argparse.ArgumentParser()
parser.add_argument("card", help="The mounted path of the SD Card")
parser.add_argument("--folder", help="Optional folder to copy the images to.")

args = parser.parse_args()

home = Path.home()

base_dir =f"{home}/Pictures/Bestof"
card = args.card

if not os.path.exists(card):
    print("No SD Card found on that mount.")
    sys.exit(1)


folder = f"{base_dir}/{args.folder}" if args.folder else base_dir

if not os.path.exists(folder):
    os.makedirs(folder)

files = glob(f"{card}/**/*.[jJ][pP][gG]", recursive=True)

for file in files[:50]:
    print(get_exif(file))




