#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle React DevTools
# @reycast.description Toggles React DevTools turning it on or off in the background
# @raycast.mode silent

# Documentation:
# @raycast.author joshika39
# @raycast.authorURL https://raycast.com/joshika39

if ! command -v react-devtools &>/dev/null; then
	echo "React DevTools is not installed. Please install it using 'npm install -g react-devtools'."
	exit 1
fi

if pgrep -x "React DevTools" >/dev/null; then
	pkill -x "React DevTools"
else
	nohup react-devtools >/dev/null 2>&1 &
fi
