#!/bin/sh

set -e

if [ -n "$(git status --porcelain)" ]; then
	echo "❌ Git working directory is dirty. Please commit or stash your changes."
	exit 1
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

TAG_AT_HEAD=$(git tag --points-at HEAD)

if [ -z "$TAG_AT_HEAD" ]; then
	echo "❌ Latest commit has no tag. Please tag it before running this script."
	exit 1
fi

VERSION="$TAG_AT_HEAD"

jq ".version = \"$VERSION\"" package.json >package.json.tmp && mv package.json.tmp package.json

git add package.json
git commit -m "release: Release version $VERSION" package.json
git push origin "$CURRENT_BRANCH"

echo "✅ package.json updated to $VERSION and pushed to $CURRENT_BRANCH."
